language: node_js

node_js: lts/*
addons:
  chrome: stable

install:
  - npm install

branches:
  only:
    - master

stages:
  - test
  - name: release
    if: branch = master AND type IN (push)

jobs:
  include:
    - stage: test
      script: npm run ci:test
    - stage: release
      node_js: lts/*
      deploy:
        script: sh ./deploy.sh
        provider: script
        skip_cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        target-branch: master
        committer-from-gh: true
        on:
          branch: master
