language: node_js

node_js: lts/*
addons:
  chrome: stable

install:
  - npm install

branches:
  only:
    - master

stages:
  - test
  - name: release
    if: branch = master AND type IN (push)

jobs:
  include:
    - stage: test
      script: npm run ci:test
    - stage: release
      node_js: lts/*
      deploy:
        script: npm run ci:deploy
        provider: script
        skip_cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        target-branch: master
        committer-from-gh: true
        on:
          branch: master
      after_success:
        - eval "$(ssh-agent -s)" #start the ssh agent
        - echo $GITHUB_SSH | base64 -D > .travis/deploy_key.pem
        - chmod 600 .travis/deploy_key.pem # this key should have push access
        - ssh-add .travis/deploy_key.pem
        - git remote add deploy git@github.com:zieka/bonsai-ui.git
